### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Eignar17** [matijaskala/compiz-boing#1]
Package compiz-gconf was not found in the pkg-config search path.
Perhaps you should add the directory containing `compiz-gconf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'compiz-gconf' found
compiling : boing.c -> build/boing.lo/bin/sh: 1: libtool: not found
Makefile:235: fallo en las instrucciones para el objetivo 'build/boing.lo'
make: *** [build/boing.lo] Error 127

**Comment by matijaskala** [comment]
Do you have the libtool-bin package installed? (`which libtool`)
I'm guessing you accidentally uninstalled some packages (probably due to a system upgrade).
Check if you still have all the packages you needed for the earth plugin.

**Comment by Eignar17** [comment]
ok is new error @matijaskala 
Package compiz-gconf was not found in the pkg-config search path.
Perhaps you should add the directory containing `compiz-gconf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'compiz-gconf' found
compiling : boing.c -> build/boing.loboing.c: In function ‘boingThink’:
boing.c:143:10: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
 texwidth = &ss->boingTex[sf->frame].width;
          ^
boing.c:144:11: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
 texheight = &ss->boingTex[sf->frame].height;
           ^
boing.c:135:11: warning: unused variable ‘boingSize’ [-Wunused-variable]
     float boingSize = boingGetLeafSize (ss->s->display);
           ^
boing.c:131:9: warning: variable ‘texheight’ set but not used [-Wunused-but-set-variable]
     int texheight;
         ^
boing.c:130:9: warning: variable ‘texwidth’ set but not used [-Wunused-but-set-variable]
     int texwidth;
         ^
boing.c:129:9: warning: variable ‘boxing’ set but not used [-Wunused-but-set-variable]
     int boxing;
         ^
boing.c: In function ‘boingMove’:
boing.c:200:11: warning: unused variable ‘boingUpdateDelay’ [-Wunused-variable]
     int   boingUpdateDelay = boingGetAutumnUpdateDelay (d);
           ^
boing.c:199:11: warning: unused variable ‘tmp’ [-Wunused-variable]
     float tmp = 1.0f / (100.0f - boingGetWindSpeed (d));
           ^
compiling : boing.c -> build/boing.lo
compiling : build/boing_options.c -> build/boing_options.lo
linking   : build/libboing.laar: `u' modifier ignored since `D' is the default (see `U')
linking   : build/libboing.la

**Comment by Eignar17** [comment]
view image for your comfort
![screenshot at 2017-05-04 16 42 45](https://cloud.githubusercontent.com/assets/8561550/25726222/d451800c-30e8-11e7-9e78-e407b0be78b0.png)

**Comment by Eignar17** [comment]
Package compiz-gconf was not found in the pkg-config search path.
Perhaps you should add the directory containing `compiz-gconf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'compiz-gconf' found
compiling : boing.c -> build/boing.loboing.c: In function ‘boingThink’:
boing.c:128:11: warning: unused variable ‘boingSize’ [-Wunused-variable]
     float boingSize = boingGetLeafSize (ss->s->display);
           ^
compiling : boing.c -> build/boing.lo
compiling : build/boing_options.c -> build/boing_options.lo
linking   : build/libboing.laar: `u' modifier ignored since `D' is the default (see `U')
linking   : build/libboing.la
is new bug @matijaskala

**Comment by Eignar17** [comment]
Package compiz-gconf was not found in the pkg-config search path.
Perhaps you should add the directory containing `compiz-gconf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'compiz-gconf' found
install   : /home/mayra/.compiz/plugins/libboing.so
install   : /home/mayra/.compiz/metadata/boing.xml
install   : build/compiz-boing.schemabuild/compiz-boing.schema:1: parser error : Document is empty
install   : build/compiz-boing.schema
install   : /home/mayra/.compiz/images/ball-01.png
install   : /home/mayra/.compiz/images/ball-07.png
install   : /home/mayra/.compiz/images/ball-11.png
install   : /home/mayra/.compiz/images/ball-00.png
install   : /home/mayra/.compiz/images/ball-06.png
install   : /home/mayra/.compiz/images/ball-12.png
install   : /home/mayra/.compiz/images/ball-08.png
install   : /home/mayra/.compiz/images/ball-13.png
install   : /home/mayra/.compiz/images/ball-02.png
install   : /home/mayra/.compiz/images/ball-10.png
install   : /home/mayra/.compiz/images/ball-14.png
install   : /home/mayra/.compiz/images/ball-04.png
install   : /home/mayra/.compiz/images/ball-15.png
install   : /home/mayra/.compiz/images/ball-09.png
install   : /home/mayra/.compiz/images/ball-03.png
install   : /home/mayra/.compiz/images/ball-05.png
